[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "solady/=lib/solady/src/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" } 