[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "solady/=lib/solady/src/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
scroll_sepolia = "${SCROLL_SEPOLIA_RPC_URL}"
zircuit = "${ZIRCUIT_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
scroll_sepolia = { key = "${SCROLLSCAN_API_KEY}", url = "${SCROLLSCAN_API_URL:https://api-sepolia.scrollscan.com/api}" }
zircuit = { key = "${ZIRCUIT_API_KEY}", url = "${ZIRCUIT_API_URL:https://testnet.explorer.zircuit.com/api}" }