[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "solady/=lib/solady/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
scroll = "${SCROLL_SEPOLIA_RPC_URL}"
zircuit = "${ZIRCUIT_RPC_URL}"
